let productos = [

    {
        nombre: "PORTATIL ASUS ROG G513 HF070 RYZEN 7 4800H 16G (2×8) 3200MHz NVMe 512G 4G RTX3050 15,6″ IPS 300Hz TC RGB W10",
        precio: 6455000,
        popularidad: 5,
        fotos: ["https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto1.png?alt=media&token=66ee5221-f5f9-45dd-9660-53f948188607", "https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto2.png?alt=media&token=c2241b35-b463-4620-bd7c-42654d7fa734"],
        descripcion: "Eleva tu estilo al siguiente nivel con una estética deportiva disponible en color Original Black jugando en cualquier lugar con un chasis hasta un 7% más pequeño que las generaciones anteriores. Sutiles recortes e íconos adornan el exterior y la parte inferior del portátil y le dan un look inconfundible desde cualquier ángulo. Ilumina tu entorno con acentos Aura Sync que brillan en el logotipo metálico de ROG, el teclado retroiluminado y la barra de luz envolvente. Al disponer de más espacio podrás navegar con mayor precisión y comodidad. El touchpad está recubierto de un cristal mate que ofrece una sensación de calidad y lo hace más resistente. Sistema Operativo: Windows 10 Home – ASUS recomienda Windows 11 Pro para empresas, Actualización gratuita a Windows 11 (si está disponible, consulte el disclaimer).Procesador: AMD Ryzen™ 7 4800H 2.9 GHz (Caché 8M, hasta 4.2 GHz).Grafica: NVIDIA® GeForce RTX™ 3050 Laptop GPU, With ROG Boost up to 1840MHz at 80W (95W with Dynamic Boost), 4GB GDDR6. Pantalla: 6 pulgadas FHD (1920 x 1080) 16:9. Pantalla antireflejo sRGB:100.00%. Adobe:75.35%. Refresh Rate:300Hz. Response Time:3ms IPS-level Adaptive-Sync Optimus. Memoria RAM: 8GB DDR4-3200 SO-DIMM x 2, Max Capacity: 32GB.Almacenamiento: SSD 512GB M.2 NVMe™ PCIe® 3.0. Puertos: 1x 3.5mm Combo Audio Jack. 1x HDMI 2.0b. 1x USB 3.2 Gen 2 Tipo C compatible con pantallas / entrega de alimentación. 3x USB 3.2 Gen 1 Type-A. Teclado y Touchpad: Teclado chiclet retroiluminado 4 zonas RGB Touchpad.Cámara: FHD 1080P@60FPS externa cámara. Audio: Audio por Dolby Atmos. AI noise-canceling technology. Micrófono incorporado. 2x 1.5W speaker. Redes: Wi-Fi 6(802.11ax) (Dual band) 2*2 + Bluetooth 5.1 (*BT version may change with OS upgrades.) -RangeBoost.Batería: 56WHrs, 4S1P, 4-cell Li-ion.Peso: 2.10 Kg (4.63 lbs).Dimensiones (A x P x A): 35.4 x 25.9 x 2.06 ~ 2.59 cm (13.94″ x 10.20″ x 0.81″ ~ 1.02″)."
    },
    {
        nombre: "PORTATIL ASUS TUF FX506LH-HN004 CORE i5 10300H 8G MVMe 512G 4G GTX 1650 15,6″IPS FHD 144Hz ENDLESS",
        fotos: ["https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto3.png?alt=media&token=0cd01295-f72c-4054-a992-70d418325d27", "https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto4.png?alt=media&token=06282d06-9aa7-46ea-b3b1-a568d8ede17a"],
        precio: 4048000,
        popularidad: 4,
        descripcion: "Sistema operativo: Sin sistema operativo. Procesador: Procesador Intel® Core™ i5-10300H 2.5 GHZ (8M Cache, hasta 4.5 GHz, 4 cores) Gráficos: NVIDIA® GeForce® GTX 1650, GDDR6 de 4 GB. Pantalla: 15,6″ – 39,62 cm, FHD (1920 x 1080) 16:9, Anti reflejo, sRGB 62.5%, Adobe 47.1%, Tasa de refresco 144 Hz, Nivel IPS, OptimusMemoria: 8GB DDR4 SO-DIMM (2933MHz) Capacidad máxima 32GB. Almacenamiento: SSD M.2 NVMe™ PCIe® 3.0 de 512 GB. Puertos de E/S: 5mm Combo Audio Jack 1x HDMI 2.0b 1 x USB 2.0 tipo A 2 x USB 3.2 de 1.ª generación tipo A 1 x USB 3.2 de 2.ª generación tipo C, compatible con DisplayPort/suministro de energía/G-SYNC 1x USB 3.2 Gen 1 Type-C support DisplayPort™ / G-SYNC (El dispositivo cuenta con solo un puerto tipo C, a velocidades de generación 2 o generación 1, según el modelo). 1x USB 3.2 Gen 2 Type-C support DisplayPort™ / G-SYNC Teclado y Touchpad:  Teclado tipo chiclet retroiluminado RGB Touchpad Cámara: HD 720 px Audio: Software DTS. Matriz de micrófonos incorporada. Altavoz incorporado. 2 x altavoz de 1 W con tecnología AMP inteligente. Redes y comunicaciones: Wi-Fi 6(802.11ax)+Bluetooth 5.1 (Dual band) 2*2;(*La version BT puede cambiar con las actualizaciones del Sistema operativo.) Batería: 48 WHrs, 3S1P, 3 celdas de iones de litio Fuente de alimentación: ø 6,0. Adaptador de CA de 150 W. Salida: 20 V CC, 7,5 A, 150 W. Entrada: 100 ~ 240 V CA, 50/60 Hz universal. Peso: 2.30 Kg. Dimensiones: 35.9 x 25.6 x 2.47 ~ 2.49 cm"
    },
    {
        nombre: "PORTATIL ASUS VIVOBOOK K513EA-BQ1796 i5 1135G7 8G NVMe 512G INTL IRIS 15,6″IPS FHD HUELLA ENDL PLATA",
        fotos: ["https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto5.png?alt=media&token=78e96bed-42ff-44f4-94fa-6ee03aba068a", "https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto6.png?alt=media&token=0ee38cf1-73bf-45cf-a4d8-0db87b5b5d9a"],
        precio: 2971000,
        popularidad: 3,
        descripcion: "Usa tu nueva VivoBook, en color negro Indie Black o Transparent Silver para trabajar, estudiar o entretenerte y disfruta de la gran fluidez que te brinda hasta su Procesador Intel® Core™ i7 de 11ª generación, de 4 núcleos, y la gran capacidad de su almacenamiento híbrido que combina las altas velocidades de datos de un SSD con las grandes capacidades de un HDD, brindándole lo mejor de ambos mundos para aumentar la productividad. Además, con la nueva tecnología ASUS Intelligent Performance Technology tendrás un incremento de hasta un 40% más en performance, batería de larga duración durante todo el día y un diseño exclusivo que mantendrá su temperatura adecuada para un mayor rendimiento. VivoBook tiene que ver con la autoexpresión y su aspecto atrevido hace una declaración. De peso liviano, chasis de metal y pantalla NanoEdge de bordes ultradelgados para una mayor inmersión visual, ASUS VivoBook te mantiene productivo y entretenido, sin importar dónde te encuentres. Sistema operativo: Windows 10 Home – ASUS recomienda Windows 10 Pro para empresas. Procesador: Procesador Intel® Core™ i5-1135G7; 0,9-2,4 GHz (caché de 8M; hasta 4,2 GHz). Gráficos: Intel Iris Xᵉ Graphics (available for Intel® Core™ i5/i7/i9 with dual channel memory). Pantalla: 15,6 pulgadas, HD (1366 × 768) 16:9, Panel de nivel IPS, Retroiluminación LED, 250 nits, NTSC: 45 %, Anti-glare display, Pantalla táctil, Screen-to-body ratio: 85% Memoria: Memoria DDR3 de 8 GB en panel. Almacenamiento: SSD de 512 GB M.2 NVMe™ PCIe® 3.0 Ranuras de expansión (incluye las utilizadas): 1x ranura DDR4 SO-DIMM. 1x M.2 2280 PCIe 3.0×2. HDD SATA 1x STD 2,5 in. Puertos de E/S: 1x USB 3.2 Gen 1 Tipo A. 1x USB 3.2 Gen 1 Tipo C. 2x USB 2.0 Tipo A. 1x HDMI 1.4. 1x salida auricular. Lector de tarjeta micro SD. Lector de tarjeta micro SD 4.0. Teclado y Touchpad:  Teclado tipo chiclet con teclado numérico, Recorrido de tecla de 1,4 mm. Cámara: HD 720. Audio: Audio de ICEpower®. Altavoz incorporado. Micrófono incorporado. Harman/Kardon (normal). Redes y comunicaciones: WiFi 5(802.11ac)+Bluetooth 4.1 (banda dual) 1 x 1. Batería: 42 Wh, 3S1P, 3 celdas Li-ion. Fuente de alimentación: ø 4.0; adaptador 65 W CA; Salida: 19 V CC, 3,42 A, 65 W; Entrada: 100~240 V CA 50/60 Hz universal. Peso: 1.80 kg (3.97 lbs). Dimensiones: 35.90 x 23.50 x 1.79 ~ 1.79 cm (14.13″ x 9.25″ x 0.70″ ~ 0.70″)"
    },
    {
        nombre: "PORTATIL ASUS VIVOBOOK X415EA EK1183 i5 1135G7 8G NVMe 256 INTEL IRIS 14″FHD HULLA ENDL GRIS",
        fotos: ["https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto7.png?alt=media&token=3200d05d-e888-4e58-a093-fbb5a4e6c232", "https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto8.png?alt=media&token=3d84fc09-c51c-4379-afa3-07b1ae44f715"],
        precio: 2081000,
        popularidad: 3,
        descripcion: "Su pantalla NanoEdge cuenta con amplios ángulos de visión de 178 ° y un acabado mate .anti reflejanterecubrimiento para una experiencia verdaderamente cautivadora. ASUS X415 tiene un diseño de almacenamiento dual para brindarle los beneficios de un rendimiento de datos ultrarrápido y una gran capacidad de almacenamiento. Instale aplicaciones en el SSD para tiempos de carga y respuesta más rápidos, y use el HDD para almacenar archivos grandes como películas, bibliotecas de música y álbumes de fotos. ASUS X415 también es compatible con la tecnología de memoria Intel® Optane™ 1 para que las aplicaciones se carguen más rápido y la multitarea se sienta más fluida. La pantalla NanoEdge le da a ASUS X415 un área de pantalla amplia para una experiencia de visualización inmersiva para trabajar y jugar. Suvista ampliaEl panel FHD cuenta con una anti reflejante Recubrimiento para reducir las distracciones no deseadas de los reflejos y los reflejos irritantes, para que pueda concentrarse realmente en lo que está frente a usted. Color: Gris. Sistema operativo: Endless.Procesador: Procesador Intel® Core™ i5-1135G7 2,4 GHz. Gráficos: Intel Iris Xᵉ (disponibles para Intel® Core™ i5 con memoria de doble canal). Monitor: 14,0 pulgadas, FHD (1920 x 1080) relación de aspecto 16:9. Memoria: DDR4 en placa, 8 GB DDR4 SO -DIMM. Almacenamiento: SSD M.2 NVMe™ PCIe® 3.0 de 256 GB SSD. Puertos de E/S: 1 USB 3.2 Gen 1 tipo A. 1 USB 3.2 Gen 1 tipo C. 2 USB 2.0 tipo A. 1 HDMI 1.4. 1 conector de audio combinado de 3,5 mm 1 lector de tarjetas Micro SD de entrada de CC (en el modelo seleccionado). Cámara: cámara vga. Audio: SonicMaster. Altavoz integrado. Micrófono integrado. Compatible con Cortana. Red y Comunicación: Wi-Fi 5 (802.11ac) (Doble banda) 1*1 + Bluetooth 4.1. Batería: 37WHrs, 2S1P, iones de litio de 2 celdas. Dimensiones (An. x Pr. x Al.):  32,54 x 21,60 x 1,99 cm (12,81″ x 8,50″ x 0,78″)"
    },
    {
        nombre: "PORTATIL GIGABYTE AORUS 15P NVIDIA GEFORCE RTX 3060 CORE i7 11800H 16G(2×8)3200 NVMe GN4 512G +15,6″IPS240H WIN10",
        fotos: ["https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto9.png?alt=media&token=0eaf8d4b-c856-44d6-ad3b-a43525805597", "https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto10.png?alt=media&token=7d62411b-812b-4d01-85d4-74c695b0f23b"],
        precio: 8729000,
        popularidad: 5,
        descripcion: "Sistema operativo: Windows 10 Home Gratis Actualice a Windows 11 1 cuando esté disponible (consulte a continuación).CPU: Intel® Core™ i7-11800H de 11.ª generación (2,3 GHz~4,6 GHz).Pantalla: Pantalla LCD antirreflejo FHD de bisel fino de 15,6″ 1920 x 1080 con nivel de IPS (240 Hz, 72% NTSC).Memoria del sistema: 2 ranuras DDR4 (DDR4-3200, máx. 64 GB).Gráficos de vídeo: Gráficos Intel® UHD NVIDIA® GeForce RTX™ 3060 GPU para computadora portátil 6GB GDDR6. Boost Clock 1605 MHz, potencia máxima de gráficos 115 W. Admite tecnologías NVIDIA Max-Q:. Dynamic Boost 2.0, BAR redimensionable y tecnología con capacidad Advanced Optimus™. Almacenamiento: 2 ranuras SSD M.2 (tipo 2280, admite 1x NVMe PCIe Gen3 y SATA / 1x NVMe PCIe Gen4), La capacidad de almacenamiento puede variar según el país y la región. Póngase en contacto con sus distribuidores o minoristas locales para obtener la información más reciente sobre el producto. Tipo de teclado: Teclado AORUS Fusion estilo isla con control retroiluminado por tecla. Puerto de E/S: 3x USB 3.2 Gen1 (Tipo-A). 1x Thunderbolt™ 4 (tipo C). 1x HDMI 2.1. 1x mini DP 1.4. 1x conector combinado de audio de 3,5 mm. 1x lector de tarjetas SD UHS-II. 1x conector de entrada de CC. 1x RJ -45. Audio: 2 altavoces de 2 vatios. Micrófono. Tecnología DTS: X® Ultra Audio. Comunicaciones: LAN: 10/100/1000/2500 Mbps Ethernet. WLAN: Intel® AX200 Wireless (802.11ax, compatible con a/b/g/n/ac/ax). Bluetooth: Bluetooth® V5.2. Cámara web: Cámara de alta definición.Seguridad: TPM basado en firmware, compatible con la tecnología Intel® Platform Trust Technology (Intel® PTT).Batería: Polímero de Li hasta 99Wh.Adaptador: 230W.Dimensiones (An. x Pr. x Al.): 35,7 x 25,4 x 2,36 ~ 2,74 cm. 14,0 x 10,0 x 0,93 ~1,08 pulgadas. Las dimensiones de la computadora portátil pueden variar según la configuración, el proceso de fabricación y el método de medición, consulte la situación real.Peso: ~ 2,29 kg ~ 5,05 libras."
    },
    {
        nombre: "PORTATIL GIGABYTE G5 GD NVIDIA GEFORCE RTX 3050 CORE i5 11400H 16G (2×8) 3200 NVMe GN4 512G 4G 15,6″IPS 144Hz WIN10",
        fotos: ["https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto11.png?alt=media&token=c4cd3310-f7c6-4a4e-9bf1-2e8d345d6f0e", "https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto12.png?alt=media&token=ce7a0a85-06a1-454f-9a4b-cf2c11f1009b"],
        precio: 6029000,
        popularidad: 4,
        descripcion: "Sistema operativo: Windows 10 Home.Procesador: Core™ i5-11400H.Pantalla: Pantalla LCD antirreflejo de nivel IPS FHD con bisel delgado de 15,6″ de 1920 x 1080 (144 Hz, 72 % NTSC viene con Core i5 Procesador).Memoria del Sistema: 2 ranuras DDR4 (máx. 64 GB), GIGABYTE adopta memoria DDR4-3200. La plataforma Intel de 10.ª generación admite una frecuencia de hasta 2933 MHz..Conjunto de chips: Conjunto de chips Intel® HM470 Express para dispositivos móviles.Tarjetas Gráficas: NVIDIA® GeForce RTX™ 3050 Laptop GPU 6GB GDDR6. Disco duro: 1 ranura para HDD/SSD de 2,5” (solo admite 7 mm o menos). 2 ranuras para SSD M.2 (tipo 2280, admite 1 NVMe PCIe y SATA/ 1 NVMe PCIe) Admite 3 sistemas de almacenamiento. La capacidad de almacenamiento puede variar según el país y la región. Póngase en contacto con sus distribuidores o minoristas locales para obtener la información más reciente sobre el producto. Tipo de teclado: Teclado retroiluminado de un solo color para todas las zonas con ajuste de LED de 15 colores. Puertos E/S: 1x USB2.0 Tipo-A. 1x USB3.2 Gen1 Tipo-A. 1x USB3.2 Gen2 Tipo-A. 1x HDMI 2.0 (con HDCP). 1x mini DP 1.4. 1x DisplayPort 1.4 Tipo-C sobre USB 3.2 Gen 2. 1x Conector combinado de audio. 1x Conector de micrófono. 1 lector de tarjetas SD 1 conector de entrada de CC 1 RJ-45. Audio: 2 altavoces de 2 vatios. Micrófono de doble matriz Nahimic 3. Comunicaciones: LAN: RTL8411B REALTEK (1G) Ethernet WLAN: Intel® AX200 Wireless o Intel® AX201 Wireless (802.11ax, compatible con a/b/g/n/ac/ax). Bluetooth: Bluetooth® V5.2. Cámara web: cámara de alta definición.Seguridad: TPM basado en firmware, compatible con Intel® Platform Trust Technology (Intel® PTT).Bateria: Li-ion 48.96Wh.Adaptador: 180W, El adaptador puede diferir según el país y la región. Póngase en contacto con sus distribuidores o minoristas locales para obtener la información más reciente sobre el producto."
    },
    {
        nombre: "PORTATIL GIGABYTE U4 UD CORE i7 1195G7 16G(2×8)3200 NVMe GN4 512G 14,0″60Hz WIN10 SLIM ULTRALIVIANO",
        fotos: ["https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto13.png?alt=media&token=04c18125-e9fd-41f6-a3b5-43de931c02c2", "https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto14.png?alt=media&token=1ee378b8-946e-483e-8a3b-ae2ee9d11dca"],
        precio: 6137000,
        popularidad: 4,
        descripcion: "Sistema operativo: Windows 10 Home Gratis Actualice a Windows 11 1 cuando esté disponible (consulte a continuación).CPU: Intel® Core™ i7-1195G7 de 11.ª generación (2,9 GHz~5,0 GHz).Pantalla: Pantalla LCD antirreflejo de nivel IPS FHD 1920×1080 de 14,0″ con bisel delgado.Memoria del sistema: 1x ranuras DDR4 (DDR4-3200 8GB a bordo, Max 16GB).Gráficos de vídeo: Gráficos Intel® Iris® Xe.Almacenamiento: 2 ranuras SSD M.2 (tipo 2280, admite 1 NVMe PCIe Gen3 y SATA/ 1 NVMe PCIe Gen4), La capacidad de almacenamiento puede variar según el país y la región. Póngase en contacto con sus distribuidores o minoristas locales para obtener la información más reciente sobre el producto.Tipo de teclado: Teclado retroiluminado (color blanco). Puerto de E/S: 1x USB 3.2 Gen1 (Tipo-A). 1x USB 3.2 Gen2 (Tipo-A) 1x Thunderbolt™ 4 (Tipo-C) (carga USB4 / DP / PD) 1x HDMI 2.0 (con HDCP) 1x Conector combinado de audio 1x Lector de tarjetas MicroSD 1 conector de entrada de CC. Audio: 2 altavoces de 1,5 vatios. Micrófono de doble matriz DTS:X® Ultra. Comunicaciones: WLAN: Intel® AX201 inalámbrico (802.11ax, compatible con a/b/g/n/ac/ax) Bluetooth: Bluetooth® V5.2.Cámara web: Cámara de alta definición.Seguridad: Kensington® Lock, Firmware-based TPM, compatible con Intel® Platform Trust Technology (Intel® PTT).Batería: Li-ion 36Wh.Adaptador: 65W.Dimensiones (An. x Pr. x Al.): 32,2 (ancho) x 21,68 (profundidad) x 1,49 ~ 1,72 (alto) cm 12,68 (ancho) x 8,54 (profundidad) x 0,59 ~ 0,68 (alto) pulgadas. Las dimensiones de la computadora portátil pueden variar según la configuración, el proceso de fabricación y el método de medición, consulte la situación real.Peso: ~990 g, 2,18 libras, El peso de la computadora portátil puede variar según la configuración, el proceso de fabricación y el método de medición, consulte la situación real"
    },
    {
        nombre: "PORTATIL MSI ALPHA 17-B5EEK RYZEN 7 5800H 16G 2×8, 3200 M2 NVMe 512G 8G RX6600 17,3″144H TC RGB FREE",
        fotos: ["https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto15.png?alt=media&token=8f6fdcad-e8d7-4f50-b112-9c21d6d81a43", "https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto16.png?alt=media&token=acbab27d-5222-4538-9f95-8526c298a674"],
        precio: 7642000,
        popularidad: 5,
        descripcion: "Con la solución térmica exclusiva de MSI, Cooler Boost 5, potencia el rendimiento completo de la CPU y la GPU. Además, la pantalla para juegos de 144 Hz proporciona imágenes nítidas y fluidas para que los jugadores nunca pierdan el ritmo. ¡Aprovecha Alpha 17 y vuela como un trueno en el campo de batalla del juego!. Al igual que el pájaro del trueno que vuela por el cielo, Alpha 17 tiene un diseño conciso y elegante. El chasis de metal completamente negro brinda texturas premium y de calidad. Es una elección perfecta para aquellos que aman el estilo robusto y discreto. ¡Toma Alpha 17 ahora para derrotar al enemigo!. Construido con la última y revolucionaria tecnología de 7nm, el procesador móvil AMD Ryzen ™ 7 5800H con gráficos Radeon ™ RX 6600M proporciona un rendimiento del calibre de una computadora de escritorio en computadoras portátiles para juegos, disfrute de experiencias multimedia y de juegos envolventes. * Probado con el procesador móvil Ryzen ™ 7 5800H con gráficos Radeon ™ RX 6600M y memoria DDR4-3200 de doble canal. Puede variar según la configuración. CPU: AMD Ryzen ™ 7 5800 H.SO: Windows 10 Home.Monitor: 17.3 «FHD (1920 x 1080), 144 Hz, nivel IPS.Gráficos: AMD Radeon ™ RX 6600M con 8GB GDDR6.Memoria: DDR4-3200 Tipo de memoria 2 ranuras Número de ranuras SO-DIMM Máx. 64 GB Capacidad máxima.Capacidad de almacenamiento: 2 ranuras SSD M.2 (NVMe PCIe Gen3).Cámara web: Tipo HD (30 fps a 720p).Teclado: con retroiluminación RGB.Comunicación: Gb LAN 802.11 ax Wi-Fi 6 + Bluetooth v5.1.Conector de audio: 1x conector combinado de entrada de micrófono / salida de auriculares. Puertos de e / s: 1x USB2.0 tipo A 1x RJ45 1x (4K a 60Hz) HDMI 1x Tipo-C (USB3.2 Gen1 / DP) 2x USB3.2 Gen1 tipo A. Batería: 4 celdas.Adaptador de ca: Adaptador de 180W.Dimensión (wxdxh): 398 x 273 x 24,2 mm.Peso (con batería): 2,55 kilogramos."
    },
    {
        nombre: "PORTATIL MSI KATANA GF76-11UC CORE i7 11800H 16G (2×8) 3200 M2 NVMe 512G 4G RTX 3050 17,3″ 144H FHD FREE",
        fotos: ["https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto17.png?alt=media&token=6e20a3e2-94b2-475c-9c06-44aa7ee8ef7e", "https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto18.png?alt=media&token=bf447dec-93bf-4c26-be79-56f07185fe3c"],
        precio: 6037000,
        popularidad: 3,
        descripcion: "La «Espada del Dragón» fue forjada por el Clan del Dragón y no hay arma que pueda compararse con su poder. Cada golpe provoca una ráfaga de viento como un huracán y cada golpe enciende el cielo en una tempestad de fuego. Ahora, toma la Hoja del Dragón, dotada con sus poderes, y lucha por alcanzar nuevos horizontes. Con los nuevos procesadores de la 11ª Gen. Intel® Core™ i7, con hasta un 40% más de rendimiento que la generación anterior. Consigue una mayor potencia con este procesador de 8 núcleos que admite una frecuencia dual core de hasta 4,6 GHz para maximizar la eficiencia en el juego, el trabajo multitarea y la productividad. Las GPUs GeForce RTX™ Serie 30 ofrecen el máximo rendimiento para gamers y creadores. Están equipadas con Ampere -la arquitectura RTX de segunda generación de NVIDIA-, con nuevos núcleos RT, Tensor Cores y multiprocesadores de transmisión para ofrecer los gráficos con trazado de rayos más realistas y las funciones de IA más avanzadas. Sistema Operativo: Sin sistema operativo.Procesador: Intel® Core™ i7-11800H.Grafica: NVIDIA® GeForce RTX™3050. GDDR6 4GBPantalla: 17.3″ 144Hz 45% NTSC. FHD (1920*1080)Memoria RAM: DDR4 8GB*2 (3200MHz). 2 Slots (64GB Max Capacity).Almacenamiento:  512gb NVMe PCIe Gen3x4 SSD. 1x ranuras M.2 SSD (NVMe PCIe Gen3)Lan: 1x RJ45Wlan: Intel Wi-Fi 6 AX201(2*2 ax)Bluetooth: BT5.1Camara: HD (30fps@720p).USB: 2x Tipo A USB3.2 Gen1, 1x Tipo A USB2.0USB tipo C: 1x Tipo C USB3.2 Gen1Puertos de video: 1x (4K @ 60Hz) HDMIPuertos de audio: 1x Mic-in/Headphone-out Combo JackAdaptador de corriente: Adaptador de 180W.Batería: 3 cell , 53.5WhrPeso: 2.3 kgTeclado: Teclado retroiluminado en rojo."
    },
    {
        nombre: "PORTATIL XPG XENIA14 ULTRALIVIANO i7 1165G7 NVMe GN4 512G 16G 3200MHz INTEL IRIS 14″HD THBOLT BTH W10",
        fotos: ["https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto19.png?alt=media&token=9d0f13ba-037f-49e1-81c3-c653007ee475", "https://firebasestorage.googleapis.com/v0/b/tiendasuradp.appspot.com/o/producto20.png?alt=media&token=23dffbf8-3ce2-45bc-b40a-77ada11155fd"],
        precio: 6361000,
        popularidad:4,
        descripcion: "11º procesador Gen Intel® Core™ i7/ con gráficos Intel® Iris® Xe Windows 10 Home Advanced Actualización gratuita a Windows 11 cuando esté disponible (consulta más abajo) Carcasa delgada y ligera de aleación de magnesio 970g PCIe Gen4 SSD – XPG GAMMIX S50 LITE de 512 GB preinstalada Memoria premium XPG 3200MHz DDR4 de 16 GB preinstalada Selección versátil de los mejores puertos I/O en su clase Marco superestrecho de 2 mm con 92% proporción pantalla a cuerpo Pantalla precisa y brillante de 14″, 16:10 Tecnología Thunderbolt™ 4 Compatible con Wi-Fi 6 y Bluetooth 5.1 Hasta 10 horas de batería y carga rápida Cámara HD IR con Windows Hello Support. Aprovechando el ADN de XPG en los dispositivos de almacenamiento, el XPG XENIA 14 viene equipado con la unidad de estado sólido XPG PCIe Gen4 más reciente: XPG GAMMIX S50 Lite. Disfrute de un nuevo nivel de rendimiento en juegos con velocidades de carga mejoradas hasta dos veces más rápidas que las PCIe Gen3 y ocho veces más rápidas que las unidades de estado sólido SATA tradicionales. Procesador: 11th Gen Intel® Core™ i7-1165G7 Sistema Operativo: Windows 10 Home Advanced, Actualización gratuita a Windows 11* Gráficos: Gráficos Intel® Iris® Xe integrados Pantalla: Panel IPS mate WUXGA 16:10 (1920 × 1200) de 14″ y 60 Hz 100 % sRGB, 400 nits. Bisel estrecho de 2 mm (relación de pantalla del 92 %) Almacenamiento: 1 ranura PCIe Gen4 M.2 2280: Unidad de estado sólido XPG GAMMIX S50 Lite PCIe Gen 4×4 NVMe de 512 GB 1 ranura PCIe Gen3 M.2 2280: No ocupada Memoria: 1 ranura A SO-DIMM XPG HUNTER DDR4-3200 MHz de 16 GB (preinstalada) 1 ranura B SO-DIMM: No ocupada Capacidad máx.:64GB Batería: 53 Whr con soporte de carga rápida. Teclado:  Membrana silenciosa Retroiluminación blanca Recorrido de 1,2 mm Panel táctil: Panel táctil/de clic de vidrio con soporte para controlador de panel táctil de precisión de Microsoft Red: Intel® Wi-Fi 6, AX201, Gigabit Ethernet, Bluetooth 5.1 Puertos de E/S: 1 Thunderbolt™ 4 (Tipo-C / USB 4 / DP 1.4a) 1 USB 3.2 Gen2 Tipo-C 2 USB 3.2 Gen1 Tipo-A 1 Video Port 1 lector de tarjeta (UHS-I, SD/SDHC/SDXC) 1 Audio combinado de 3,5 mm 1 conector de alimentación Cámara: HD 720P IR con compatibilidad con Windows Hello Dimensiones (L x An x Al): 215 x 308,8 x 15 mm, 8,46″ x 12,15″ x 0,59″ Peso: 970g/2,13lb"
    }
]

let fila = document.getElementById("fila")

//RECORRIENDO EL ARREGLO
productos.forEach(function(producto){
    
    //Creando un div desde JS
    let columna = document.createElement("div")
    columna.classList.add("col")

    //Creando una tarjeta
    let tarjeta = document.createElement("div")
    tarjeta.classList.add("card", "shadow", "text-center", "h-100", "p5")

    //Creando una imagen
    let imagen = document.createElement("img")
    imagen.classList.add("img-fluid", "w-100")
    imagen.src = producto.fotos[0]

    //DETECTANDO EVENTO DEL MOUSE
    imagen.addEventListener("mouseover", function(){
        imagen.src = producto.fotos[1]
    })
    imagen.addEventListener("mouseleave", function(){
        imagen.src = producto.fotos[0]
    })

    //Crear nombre
    let nombre = document.createElement("h3")
    nombre.classList.add("fw-bold")
    nombre.textContent = producto.nombre
    
    //Crear precio
    let precio = document.createElement("h2")
    precio.classList.add("fw-bold")
    precio.textContent = ("$" + producto.precio)

    //Crear popularidad
    let popularidad = document.createElement("h4")
    popularidad.classList.add("fw-bold")
    popularidad.textContent = (producto.popularidad)
    
    //Creando la descripción
    let descripcion = document.createElement("p")
    descripcion.classList.add("text-danger", "d-none")
    descripcion.textContent = producto.descripcion
    
    //Definiendo padres e hijos
    tarjeta.appendChild(imagen)
    tarjeta.appendChild(nombre)
    tarjeta.appendChild(precio)
    tarjeta.appendChild(popularidad)
    tarjeta.appendChild(descripcion)
    columna.appendChild(tarjeta)
    fila.appendChild(columna)

})